### ISSUE TITLE
Invisible/uninstallable app

### ISSUE THREAD

**Issue by eson57** [abertschi/sailfish-headless-keyboard-dbus#1]
Hi,

Since last update, headless-keyboard is not visible in settings or anywhere. Thought I could try reinstall, but it is also not uninstallable. Se screen...

![screen](https://svenskasprakfiler.se/tempfiles/Screenshot-23-09-15-07-30-52.png)

**Comment by abertschi** [comment]
Version 0.2+ uses a patch for maliit. A similar problem is discussed [here](https://openrepos.net/comment/9947#comment-9947).

Please try the following steps:

> The openrepos installer app is blocking the uninstallation of the application (the extension applies a patch which is undone during deinstallation. Openrepos seems to block unreversions of patches per default). Did you install the app through the openrepos installer or through manual file download and installation? If you did the later one, just press and hold on the icon on homescreen and remove the app this way. If you used the former method, reinstall the headless keyboard extension again by opening the sailfish-wlan-keyboard app, navigating to configuration/headless-mode  and pressing the download button to download the latest *.rpm file of the extension. After the reinstallation, remove the application as described above by press and holding the icon.

**Comment by eson57** [comment]
Thanks! Uninstall/Reinstall went fine but still no headless-keyboard visible.

**Comment by abertschi** [comment]
No headless-keyboard layout is necessary anymore. The latest version works with any installed keyboard layout.

**Comment by eson57** [comment]
Wow.. works amazingly well. Guess I'll have to read release notes more carefully from now. 
Thanks for your time! :+1:
